/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  // api: [
    //   'cli',
    //   'docusaurus-core',
    //   {
      //     type: 'autogenerated',
      //     dirName: 'api',
      //   },
      // ],
      
      // But you can create a sidebar manually
      
      docsSidebar: [
        'intro',
        {
          type: 'category',
          label: 'Tutorial',
          link: {
            type: 'generated-index',
            title: 'Docusaurus Guides',
            description: 'Learn about the most important Docusaurus concepts!',
            slug: '/category/docusaurus-guides', // Link para acceder al index
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: ['tutorial-basics/create-a-document', 'tutorial-basics/congratulations', 'tutorial-extras/manage-docs-versions',
            {
              type: 'category',
              label: 'Installation',
              link: {type: 'doc', id: 'intro'}, // Linkear documento al seleccionar la category
              items: [
                'tora/gus/holagus',  // Documento dentro de la subcategoría
              ],
            },
          ],
        },
      ],
      apiSidebar: [
        'api/hola',
        'tutorial-extras/manage-docs-versions',
        'tutorial-extras/translate-your-site',
      ],
      // toraSidebar: [
      //   'tora/uno'
      // ],
      toraSidebar: [{type: 'autogenerated', dirName: 'tora'}],
      
};

export default sidebars;
